# Generated by Django 4.2.7 on 2023-11-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='user_name',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
